package by.training.zorich.dal.sql_executor;

public enum HandlerType {
    ID_USER_ROLE_HANDLER,
    USER_HANDLER,
    VALIDATE_USER_HANDLER,
    USER_ADDRESS_HANDLER,
    USER_SUBSCRIPTION_HANDLER,
    LAST_INSERTED_PAYMENT_ID,
    SELECT_PAYMENT_BY_ID,
    SUBSCRIPTION_VARIANT_BY_ID;
}
