package by.training.zorich.dal.sql_executor;

public enum HandlerType {
    ID_USER_ROLE_HANDLER,
    USER_HANDLER,
    VALIDATE_HANDLER,
    USER_ADDRESS_HANDLER,
    USER_SUBSCRIPTION_HANDLER,
    LAST_INSERTED_ITEM_ID,
    SELECT_PAYMENT_BY_ID,
    SUBSCRIPTION_VARIANT_BY_ID,
    SIMPLE_SUBSCRIPTION_VARIANT,
    ALL_PERIODICAL_TYPES,
    ALL_PERIODICAL_THEMES,
    ALL_SUBSCRIPTION_TYPES,
    PERIODICAL_BY_ID,
    ;
}
